name: e2e-workflow

on:
  push:
    branches: ['*']

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: development-simulator
  maestro_test:
    needs: [build_ios]
    type: maestro
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      flow_path: ['./__e2e__/hello-maestro.yml']
